### ISSUE TITLE
Problems when installing from Puppet Forge

### ISSUE THREAD

**Issue by ghost** [rodjek/puppet-logrotate#12]
[#] puppet module install rodjek/logrotate
Notice: Preparing to install into /etc/puppet/modules ...
Notice: Downloading from http://forge.puppetlabs.com ...
Notice: Installing -- do not interrupt ...
Error: No such file or directory - /etc/puppet/modules/logrotate/spec/fixtures/modules/logrotate/templates
Error: Try 'puppet help module install' for usage

Puppet v3.2.1

**Comment by rodjek** [comment]
Sorry about that, I should have tested the package before uploading it. I'll fix that up and put a new release on the forge today.

**Comment by rodjek** [comment]
Hmm, i'm having trouble reproducing this problem locally

```
$ puppet module install rodjek/logrotate
Notice: Preparing to install into /Users/tsharpe/.puppet/modules ...
Notice: Downloading from https://forge.puppetlabs.com ...
Notice: Installing -- do not interrupt ...
/Users/tsharpe/.puppet/modules
└── rodjek-logrotate (v1.1.0)
```

I'm pretty sure I know what it's erroring out on though (the symlinks used for the spec tests). What operating system are you running on that host?

**Comment by rodjek** [comment]
Try installing the module again, I've just pushed a new build (1.1.1) without the rspec-puppet fixtures that I believe are causing your issue.

**Comment by ghost** [comment]
It now works like a charm, thank you for a speedy resolution!
