### ISSUE TITLE
"su" option of logrotate

### ISSUE THREAD

**Issue by davidgreisler** [rodjek/puppet-logrotate#14]
Logrotate has an option to change user/group before rotating a logfile. For example "su portage portage" rotates the logfile as user portage and group portage. 

Without this option it is not possible (or I don't know how) to rotate files like the elog logfiles under Gentoo.

```
error: skipping "/var/log/portage/elog/summary.log" because parent directory has insecure permissions (It's world writable or writable by group which is not "root") 
Set "su" directive in config file to tell logrotate which user/group should be used for rotation.
```

Could you add the "su" option to the puppet module? :-)

**Comment by mjward** [comment]
+1 very important feature if your running a rails app other than root

**Comment by borisguery** [comment]
+1 I just faced this issue

**Comment by rodjek** [comment]
#19 has been merged.
