### ISSUE TITLE
The cron entries should send output to /dev/null unless failure

### ISSUE THREAD

**Issue by solomonty** [rodjek/puppet-logrotate#24]
There is too much e-mail noise from cron.

For example, here is the logrotate installed in cron.daily on RHEL/CentOS where it creates output and sends e-mail only on failure.

```
#!/bin/sh

/usr/sbin/logrotate /etc/logrotate.conf >/dev/null 2>&1
EXITVALUE=$?
if [ $EXITVALUE != 0 ]; then
    /usr/bin/logger -t logrotate "ALERT exited abnormally with [$EXITVALUE]"
fi
exit 0
```

**Comment by rodjek** [comment]
So, I guess this is one of the many differences between Debian and RedHat based distros, on Debian logrotate doesn't print anything unless there is an error.

How about something like this?

```
#!/bin/sh

OUTPUT=$(/usr/sbin/logrotate /etc/logrotate.conf 2>&1)
EXITVALUE=$?
if [ $EXITVALUE != 0 ]; then
    /usr/bin/logger -t logrotate "ALERT exited abnormally with [$EXITVALUE]"
    echo "${OUTPUT}"
fi
exit 0
```

That way the output from logrotate will still be sent via email if there is a failure.

**Comment by solomonty** [comment]
The output is not from logrotate per se but from the scripts run via postrotate.

You should be able reproduce that on Debian.

Your proposed logrotate cron entry looks good.
